title: Google Cloud Vision OCR
description: >-
  OCR your documents using Google Cloud Vision OCR. 
instructions: ''
type: object
documents:
  - selected
properties: {}
categories:
  - extraction
  - premium
cost: 
  price: 1
  amount: 1
  unit: page
version: 2
