title: Google Cloud Vision OCR
description: >-
  OCR your documents using Google Cloud Vision OCR. 
instructions: ''
type: object
documents:
  - selected
properties:
  to_tag:
    title: Tag OCR'd documents?
    type: boolean
    description: "If selected, the key/value pair of ocr_engine:azure will be added to the document as metadata"
categories:
  - extraction
  - premium
cost: 
  price: 1
  amount: 1
  unit: page
version: 2
