title: Google Cloud Vision OCR
description: >-
  OCR your documents using Google Cloud Vision OCR. 
  This Add-On uses 1 AI Credit per page. 
instructions: ''
type: object
documents:
  - selected
properties: {}
categories:
  - extraction
  - premium
cost: 
  price: 1
  amount: 1
  unit: document
