title: Google Cloud Vision OCR
description: >-
  OCR your documents using Google Cloud Vision OCR. 
  This Add-On uses AI Credits. 
type: object
documents:
  - selected
properties: {}
categories:
  - extraction
